# Generated by Django 2.1.7 on 2019-03-03 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='*required', max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('fathers_name', models.CharField(help_text='*required', max_length=30)),
                ('mothers_name', models.CharField(help_text='*required', max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10)),
                ('place', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('it', 'information technology'), ('me', 'mech'), ('ce', 'civil'), ('eee', 'eee'), ('ece', 'ece'), ('ch', 'chemical'), ('cse', 'cse')], max_length=10)),
                ('cgpa_Btech', models.FloatField(help_text='*required', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('class_10_cgpa', models.FloatField(help_text='*required', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('class_12_percentage', models.FloatField(help_text='*required', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('certifications_count', models.IntegerField()),
                ('internship', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10)),
                ('languages', models.CharField(help_text='*required', max_length=100)),
                ('sop', models.CharField(help_text='*required', max_length=500)),
                ('dob', models.DateField(help_text='*format is YYYY-MM-DD')),
            ],
        ),
    ]
