# Generated by Django 2.1.7 on 2019-03-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_details',
            name='username',
            field=models.CharField(default='y1', help_text='enter username ex:y16it***', max_length=9),
        ),
    ]
