# Generated by Django 2.1.7 on 2019-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20190304_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_details',
            name='name',
            field=models.CharField(default='full name', help_text='*required', max_length=30),
        ),
    ]
