# Generated by Django 2.1.7 on 2019-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_auto_20190317_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='applied_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text='*required', max_length=30, unique=True)),
                ('username', models.CharField(default='y1', help_text='enter username ex:y16it***', max_length=9)),
            ],
        ),
    ]
