# Generated by Django 2.1.7 on 2019-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_applied_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applied_jobs',
            old_name='username',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='applied_jobs',
            name='company_id',
            field=models.CharField(default='company id', help_text='*required', max_length=30),
        ),
        migrations.AlterField(
            model_name='applied_jobs',
            name='job_id',
            field=models.CharField(default='job id', help_text='*required', max_length=30),
        ),
    ]
