# Generated by Django 2.1.7 on 2019-03-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_auto_20190321_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_details',
            name='email',
            field=models.EmailField(default='anudeep.insvirat@gmail.com', help_text='Required. Inform a valid email address.', max_length=254),
        ),
    ]
